/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Semana8;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Programa_Hotel extends javax.swing.JFrame {
    public Programa_Hotel() {
        initComponents();
    }
    // Precios de las habitaciones por día
    private static final double TARIFA_SIMPLE = 80.0;
    private static final double TARIFA_MATRIMONIAL = 130.0;
    private static final double TARIFA_DOBLE = 140.0;
    private static final double TARIFA_TRIPLE = 180.0;
    
    // Porcentajes de descuento según la cantidad de días de hospedaje
    private static final double DESCUENTO_12_O_MAS = 0.075;
    private static final double DESCUENTO_6_A_11 = 0.05;
    private static final double DESCUENTO_3_A_5 = 0.025;
    private static final double DESCUENTO_MENOS_DE_3 = 0.0;
    
    // Cantidad de lapiceros de obsequio según el importe total a pagar
    private static final int LAPICEROS_MENOS_DE_100 = 2;
    private static final int LAPICEROS_100_A_149 = 3;
    private static final int LAPICEROS_150_O_MAS = 4;
    

    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Programa_Hotel().setVisible(true);
        }
    });
}
    
    public void calcular(String tipoHabitacion, int cantidadDias) {
    double tarifaDiaria = obtenerTarifaDiaria(tipoHabitacion);
    double subtotal = calcularSubtotal(tarifaDiaria, cantidadDias);
    double descuento = calcularDescuento(subtotal, cantidadDias);
    double totalPagar = subtotal - descuento;
    int lapiceros = calcularLapiceros(totalPagar);
    
    // Construir el mensaje con los resultados
    String resultado = "Importe Subtotal: S/. " + subtotal + "\n";
    resultado += "Importe Descuento: S/. " + descuento + "\n";
    resultado += "Importe Total a Pagar: S/. " + totalPagar + "\n";
    resultado += "Cantidad de Lapiceros de Obsequio: " + lapiceros;
    
    // Establecer el mensaje en el TextArea
    txtRes.setText(resultado);
    }
    
    private static double obtenerTarifaDiaria(String tipoHabitacion) {
        switch (tipoHabitacion) {
            case "Simple":
                return TARIFA_SIMPLE;
            case "Matrimonial":
                return TARIFA_MATRIMONIAL;
            case "Doble":
                return TARIFA_DOBLE;
            case "Triple":
                return TARIFA_TRIPLE;
            default:
                throw new IllegalArgumentException("Tipo de habitación no válido");
        }
    }
    
    private static double calcularSubtotal(double tarifaDiaria, int cantidadDias) {
        return tarifaDiaria * cantidadDias;
    }
    
    private static double calcularDescuento(double subtotal, int cantidadDias) {
        if (cantidadDias >= 12) {
            return subtotal * DESCUENTO_12_O_MAS;
        } else if (cantidadDias >= 6 && cantidadDias < 12) {
            return subtotal * DESCUENTO_6_A_11;
        } else if (cantidadDias >= 3 && cantidadDias < 6) {
            return subtotal * DESCUENTO_3_A_5;
        } else {
            return subtotal * DESCUENTO_MENOS_DE_3;
        }
    }
    
    private static int calcularLapiceros(double totalPagar) {
        if (totalPagar < 100) {
            return LAPICEROS_MENOS_DE_100;
        } else if (totalPagar >= 100 && totalPagar < 150) {
            return LAPICEROS_100_A_149;
        } else {
            return LAPICEROS_150_O_MAS;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxTipoHabitacion = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PROGRAMA HOTEL");

        jLabel2.setText("Elija un tipo de Habitaciòn:");

        cbxTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--ELEGIR--", "Simple", "Matrimonial", "Doble", "Triple" }));

        btnCalcular.setText("CALCULAR IMPORTE");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtRes.setColumns(20);
        txtRes.setRows(5);
        jScrollPane1.setViewportView(txtRes);

        jLabel3.setText("Cantidad de días hospedados: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDias))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnCalcular)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // Obtener el tipo de habitación seleccionado
        String tipoHabitacion = (String) cbxTipoHabitacion.getSelectedItem(); 
    
        // Verificar que la opción seleccionada no sea la primera (indice 0)
        if (!tipoHabitacion.equals("--ELEGIR--")) {
            // Obtener la cantidad de días ingresada por el usuario desde el JTextField txtDias
            int cantidadDias;
            try {
                cantidadDias = Integer.parseInt(txtDias.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido para la cantidad de días", "Error", 
                                                    JOptionPane.ERROR_MESSAGE);
                return; // Salir del método si no se ingresó un número válido
            }

            // Llamar al método calcular con los valores obtenidos
            calcular(tipoHabitacion, cantidadDias);
        } else {
            // Mostrar un mensaje de error si no se ha seleccionado una opción válida
            JOptionPane.showMessageDialog(this, "Por favor seleccione un tipo de habitación válido", "Error", 
                                                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /*
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbxTipoHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextArea txtRes;
    // End of variables declaration//GEN-END:variables
}
