
package Proyecto_Empresa_Software_Technology; // Paquete del proyecto

// Importación de clases necesarias
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

// Declaración de la clase Configurar_Descuentos que extiende de javax.swing.JFrame
public class Configurar_Descuentos extends javax.swing.JFrame {
    // Constructor de la clase
    public Configurar_Descuentos() {
        initComponents(); // Llama al método initComponents generado automáticamente
        //CENTRADO DE VENTANA
        this.setLocationRelativeTo(null);
        cargarDescuentos(); // Cargar los descuentos al iniciar la aplicación
    }
    
    // Método para cargar los descuentos en los JTextField
    private void cargarDescuentos() {
        // Cargar los descuentos por defecto en los JTextField
        txtDes1.setText(String.valueOf(Menu_Principal.des1));
        txtDes2.setText(String.valueOf(Menu_Principal.des2));
        txtDes3.setText(String.valueOf(Menu_Principal.des3));
        txtDes4.setText(String.valueOf(Menu_Principal.des4));
    }

    // Resto del código omitido por brevedad
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtDes1 = new javax.swing.JTextField();
        txtDes2 = new javax.swing.JTextField();
        txtDes3 = new javax.swing.JTextField();
        txtDes4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 477, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descuento 1:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descuento 2:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("CONFIGURAR DESCUENTOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        txtDes1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtDes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 140, 40));

        txtDes2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtDes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDes2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtDes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 140, 40));

        txtDes3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtDes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDes3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtDes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 140, -1));

        txtDes4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtDes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descuento 3:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descuento 4:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGuardar.setText("GUARDAR CAMBIOS EFECTUADOS");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Método para manejar el evento de clic en el botón de Guardar
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Obtener los valores ingresados en los campos de texto
        try {
            double desc1 = Double.parseDouble(txtDes1.getText());
            double desc2 = Double.parseDouble(txtDes2.getText());
            double desc3 = Double.parseDouble(txtDes3.getText());
            double desc4 = Double.parseDouble(txtDes4.getText());

            // Validar que los descuentos sean valores positivos
            if (desc1 >= 0 && desc2 >= 0 && desc3 >= 0 && desc4 >= 0) {
                // Guardar los descuentos en las variables globales
                Menu_Principal.des1 = desc1;
                Menu_Principal.des2 = desc2;
                Menu_Principal.des3 = desc3;
                Menu_Principal.des4 = desc4;

                // Mostrar un mensaje de éxito
                JOptionPane.showMessageDialog(this, "Descuentos guardados correctamente.");
            } else {
                // Mostrar un mensaje de error si los descuentos son negativos
                JOptionPane.showMessageDialog(this, "Los descuentos deben ser valores positivos.");
            }
        } catch (NumberFormatException e) {
            // Mostrar un mensaje de error si los valores ingresados no son números válidos
            JOptionPane.showMessageDialog(this, "Ingrese números válidos en los campos de descuento.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    // Método para manejar el evento de clic en el botón de Salir
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Menu_Principal newMantenimiento = new Menu_Principal();
        newMantenimiento.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed
    
    // Métodos para manejar eventos de los campos de texto
    private void txtDes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDes3ActionPerformed

    private void txtDes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDes2ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Método main para ejecutar la aplicación
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurar_Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurar_Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurar_Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurar_Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configurar_Descuentos().setVisible(true);
            }
        });
    }
    // Declaración de variables
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDes1;
    private javax.swing.JTextField txtDes2;
    private javax.swing.JTextField txtDes3;
    private javax.swing.JTextField txtDes4;
    // End of variables declaration//GEN-END:variables
}
