package Proyecto_Empresa_Software_Technology;// Paquete del proyecto

import Proyecto_Empresa_Software_Technology.Menu_Principal;
import Proyecto_Empresa_Software_Technology.Menu_Principal;
import Proyecto_Empresa_Software_Technology.Menu_Principal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
    
// Declaración de la clase Ventas que extiende de javax.swing.JFrame
public class Ventas extends javax.swing.JFrame {
    // Constructor de la clase
    public Ventas() {
        initComponents();
        //CENTRADO DE VENTANA
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtRes = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxSoftware = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCantidadLicencias = new javax.swing.JTextField();
        btnVender = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRes.setColumns(20);
        txtRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRes.setRows(5);
        jScrollPane1.setViewportView(txtRes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 262, 670, 250));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("VENTAS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo de Software:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        cbxSoftware.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxSoftware.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Elegir---", "Web", "Moviles", "Juegos", "Comercial" }));
        cbxSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSoftwareActionPerformed(evt);
            }
        });
        jPanel1.add(cbxSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 190, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de Licencias:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        txtCantidadLicencias.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtCantidadLicencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 130, 40));

        btnVender.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVender.setText("VENDER");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Método para manejar el evento de clic en el botón de Vender
    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // Obtener los datos de la venta
        String tipoSoftware = (String) cbxSoftware.getSelectedItem();
        int cantidadLicencias = Integer.parseInt(txtCantidadLicencias.getText());

        // Calcular importes y obsequios
        double importeCompra = cantidadLicencias * Menu_Principal.softPrecio[cbxSoftware.getSelectedIndex() - 1];
        double importeDescuento = calcularDescuento(cantidadLicencias, importeCompra);
        double importeAPagar = importeCompra - importeDescuento;
        String obsequio = calcularObsequio(tipoSoftware, cantidadLicencias);

        // Mostrar la boleta de venta en el JTextArea
        txtRes.setText(
            "Nombre de la empresa: " + Menu_Principal.nombreEmpresa + "\n" +
            "Tipo de software: " + tipoSoftware + "\n" +
            "Lenguaje de programación empleado: " + Menu_Principal.softLenguaje[cbxSoftware.getSelectedIndex() - 1] + "\n" +
            "Espacio que ocupa el software: " + Menu_Principal.softEspacio[cbxSoftware.getSelectedIndex() - 1] + "\n" +
            "Cantidad de licencias de software vendidos: " + cantidadLicencias + "\n" +
            "Importe compra: " + importeCompra + "\n" +
            "Importe de descuento: " + importeDescuento + "\n" +
            "Importe a pagar: " + importeAPagar + "\n" +
            "Obsequio: " + obsequio
        );
    }
    // Método para calcular el descuento según la cantidad de licencias
    private double calcularDescuento(int cantidadLicencias, double importeCompra) {
        double descuento = 0;
        if (cantidadLicencias >= 1 && cantidadLicencias <= 7) {
            descuento = importeCompra * (Menu_Principal.des1 / 100);
        } else if (cantidadLicencias >= 8 && cantidadLicencias <= 13) {
            descuento = importeCompra * (Menu_Principal.des2 / 100);
        } else if (cantidadLicencias >= 14 && cantidadLicencias <= 20) {
            descuento = importeCompra * (Menu_Principal.des3 / 100);
        } else if (cantidadLicencias > 20) {
            descuento = importeCompra * (Menu_Principal.des4 / 100);
        }
        return descuento;
    }
    
    // Método para calcular el obsequio según el tipo de software y la cantidad de licencias
    private String calcularObsequio(String tipoSoftware, int cantidadLicencias) {
        String obsequio = "";
        if (tipoSoftware.equals("Web") || tipoSoftware.equals("Comercial")) {
            int actualizaciones = cantidadLicencias / 2 * 3;
            obsequio = actualizaciones + " actualizaciones";
        } else if (tipoSoftware.equals("Juegos")) {
            int actualizaciones = cantidadLicencias / 10 * 2;
            obsequio = actualizaciones + " actualizaciones";
        }
        return obsequio;
    }//GEN-LAST:event_btnVenderActionPerformed
    
    // Método para manejar el evento de selección en el JComboBox de Software
    private void cbxSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSoftwareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSoftwareActionPerformed
    
    // Método para manejar el evento de clic en el botón de Salir
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Menu_Principal principal = new Menu_Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**s
     * @param args the command line arguments
     */
    // Método main para ejecutar la aplicación
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Declaración de variables
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVender;
    private javax.swing.JComboBox<String> cbxSoftware;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidadLicencias;
    private javax.swing.JTextArea txtRes;
    // End of variables declaration//GEN-END:variables
}
